import Styles from './page.module.css';
import Image from 'next/image';
import hero from "/public/images/hero.svg";
import Link from 'next/link';

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className={Styles.main}>
        <div className={Styles.info}>
          <h2>your best online shop destination!</h2>
          <p>
            Discover the latest fashion trends with ATOZ. Shop the new
            collection of clothing, footwear, accessories, beauty products and
            more. Order today from ATOZ.
          </p>
          <Link href="/products">
            <button>shop now</button>
          </Link>
        </div>
        <div className={Styles.hero}>
          <Image
            src={hero}
            width={350}
            height={350}
            alt="hero"
            className={Styles.heroImg}
          />
        </div>
      </div>
    </>
  );
}
