import Styles from "./contact.module.css";
export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};
const contact = () => {
  return (
    <div className={Styles.main}>
      <form>
        <label htmlFor="name">Name:</label>
        <input type="text" id="name" placeholder="Enter name" required />
        <label htmlFor="email">Email:</label>
        <input type="email" id="email" placeholder="Enter email" required />
        <label htmlFor="message">Message:</label>
        <textarea cols={100} id="message" required placeholder="Message" />
        <button>send</button>
      </form>
    </div>
  );
};

export default contact;
